language: cpp
dist: xenial
compiler:
  - gcc  # GCC 5.4.0
os:
  - linux
script:  # don't test watch_dog by default
  - mkdir build && cd build && cmake .. && make -j 4 all
  - ./utest_cs133_hw4 #--gtest_filter="-*.test_watch_dog"
after_success:
  - ./systest_cs133_hw4
